import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen1widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen1widget/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen1widget/generated/GeneratedTopappbarWidget1.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen1widget/generated/GeneratedStackedcardWidget.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen1widget/generated/GeneratedBackFINAL1Widget1.dart';

/* Frame Game Screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGameScreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -480.0,
                top: -358.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 368.0,
                child: GeneratedStackedcardWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 52.0,
                child: GeneratedButtonWidget6(),
              ),
              Positioned(
                left: 103.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 47.0,
                child: GeneratedGroup1Widget(),
              )
            ]),
      ),
    ));
  }
}
