import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedsettingswidget/generated/GeneratedTopappbarWidget5.dart';
import 'package:flutterapp/pantomimeapp/generatedsettingswidget/generated/GeneratedBackFINAL1Widget5.dart';
import 'package:flutterapp/pantomimeapp/generatedsettingswidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/pantomimeapp/generatedsettingswidget/generated/GeneratedFrame4Widget.dart';

/* Frame Settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -480.0,
                top: -354.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget5(),
              ),
              Positioned(
                left: -14.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 216.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 216.0,
                child: GeneratedFrame5Widget(),
              )
            ]),
      ),
    ));
  }
}
