import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatednewgamewidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/pantomimeapp/generatednewgamewidget/generated/GeneratedTopappbarWidget.dart';
import 'package:flutterapp/pantomimeapp/generatednewgamewidget/generated/GeneratedBackFINAL1Widget.dart';
import 'package:flutterapp/pantomimeapp/generatednewgamewidget/generated/GeneratedHorizontalcardWidget.dart';
import 'package:flutterapp/pantomimeapp/generatednewgamewidget/generated/GeneratedHorizontalcardWidget1.dart';

/* Frame New Game
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewGameWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -486.0,
                top: -358.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 172.0,
                child: GeneratedHorizontalcardWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 172.0,
                child: GeneratedHorizontalcardWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 75.0,
                child: GeneratedWidget(),
              )
            ]),
      ),
    ));
  }
}
