import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedWidget8.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedWidget9.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedBackFINAL1Widget4.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedContentWidget5.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedTopappbarWidget4.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedOscars1Widget.dart';
import 'package:flutterapp/pantomimeapp/generatedfinalscreenwidget/generated/GeneratedButtonWidget10.dart';

/* Frame Final Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFinalScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -480.0,
                top: -354.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 107.0,
                child: GeneratedContentWidget5(),
              ),
              Positioned(
                left: 87.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 52.0,
                child: GeneratedButtonWidget10(),
              ),
              Positioned(
                left: 12.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 42.0,
                child: GeneratedWidget8(),
              ),
              Positioned(
                left: 69.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 222.0,
                child: GeneratedOscars1Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 37.0,
                child: GeneratedWidget9(),
              )
            ]),
      ),
    ));
  }
}
