import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedhomeinterruptedwidget/generated/GeneratedLogoel1Widget1.dart';
import 'package:flutterapp/pantomimeapp/generatedhomeinterruptedwidget/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/pantomimeapp/generatedhomeinterruptedwidget/generated/GeneratedBackFINAL2Widget1.dart';
import 'package:flutterapp/pantomimeapp/generatedhomeinterruptedwidget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/pantomimeapp/generatedhomeinterruptedwidget/generated/GeneratedRectangle1Widget1.dart';

/* Frame Home - interrupted
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeinterruptedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -994.0,
                top: -197.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 128.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 28.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 74.0,
                child: GeneratedLogoel1Widget1(),
              ),
              Positioned(
                left: 96.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 52.0,
                child: GeneratedButtonWidget3(),
              ),
              Positioned(
                left: 96.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 52.0,
                child: GeneratedButtonWidget4(),
              )
            ]),
      ),
    ));
  }
}
