import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen3widget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen3widget/generated/GeneratedButtonWidget8.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen3widget/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen3widget/generated/GeneratedBackFINAL1Widget2.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen3widget/generated/GeneratedStackedcardWidget1.dart';
import 'package:flutterapp/pantomimeapp/generatedgamescreen3widget/generated/GeneratedTopappbarWidget2.dart';

/* Frame Game Screen 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGameScreen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -480.0,
                top: -358.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 368.0,
                child: GeneratedStackedcardWidget1(),
              ),
              Positioned(
                left: 103.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 47.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 191.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 52.0,
                child: GeneratedButtonWidget7(),
              ),
              Positioned(
                left: 13.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 52.0,
                child: GeneratedButtonWidget8(),
              )
            ]),
      ),
    ));
  }
}
