import 'package:flutter/material.dart';

/* Text Material Design components were used and copied from Material-3-Design-Kit. Cards Top App Bar Buttons Material Icons Instances were detouched from their master components and modified accordingly.
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaterialDesigncomponentswereusedandcopiedfromMaterial3D
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Material Design components were used and copied from Material-3-Design-Kit.

Cards
Top App Bar
Buttons
Material Icons

Instances were detouched from their master components and modified accordingly.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1111111111111112,
        fontSize: 18.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.10000000149011612, */
      ),
    ));
  }
}
