import 'package:flutter/material.dart';

/* Text Components
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponentsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.center,
      child: Text(
        '''Components''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 0.8333333333333334,
          fontSize: 24.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w500,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.10000000149011612, */
        ),
      ),
    ));
  }
}
