import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedsplashscreenwidget/generated/GeneratedDrawableporthdpiscreen1Widget.dart';

/* Frame Splash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomeWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -60.0,
                  top: -80.0,
                  right: null,
                  bottom: null,
                  width: 480.0,
                  height: 800.0,
                  child: GeneratedDrawableporthdpiscreen1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
