import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedButtonWidget9.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedTopappbarWidget3.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedWidget6.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedBackFINAL1Widget3.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedContentWidget4.dart';
import 'package:flutterapp/pantomimeapp/generatedscorescreenwidget/generated/GeneratedWidget2.dart';

/* Frame Score Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScoreScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -480.0,
                top: -354.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 120.0,
                child: GeneratedContentWidget4(),
              ),
              Positioned(
                left: 79.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 58.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 79.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 58.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 163.0,
                child: GeneratedWidget6(),
              ),
              Positioned(
                left: 93.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 52.0,
                child: GeneratedButtonWidget9(),
              )
            ]),
      ),
    ));
  }
}
