import 'package:flutter/material.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedContentWidget6.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedButtonWidget11.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedB1Widget.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedA1Widget2.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedBackFINAL1Widget6.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedWidget16.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedWidget17.dart';
import 'package:flutterapp/pantomimeapp/generatedfirstroundonlyscreenwidget/generated/GeneratedTopappbarWidget6.dart';

/* Frame First round ONLY screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFirstroundONLYscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -480.0,
                top: -354.0,
                right: null,
                bottom: null,
                width: 2012.0,
                height: 1171.0,
                child: GeneratedBackFINAL1Widget6(),
              ),
              Positioned(
                left: -3.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 63.0,
                child: GeneratedContentWidget6(),
              ),
              Positioned(
                left: 87.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 52.0,
                child: GeneratedButtonWidget11(),
              ),
              Positioned(
                left: 167.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 42.0,
                child: GeneratedA1Widget2(),
              ),
              Positioned(
                left: 167.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 42.0,
                child: GeneratedB1Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 39.0,
                child: GeneratedWidget16(),
              ),
              Positioned(
                left: 32.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 39.0,
                child: GeneratedWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedTopappbarWidget6(),
              )
            ]),
      ),
    ));
  }
}
